import { Inter } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Banner } from "@/components/Banner";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex h-full bg-slate-100 pt-14">
          <Sidebar />
          <main className="flex-1 relative overflow-auto px-14">
            <Banner />
            <Toaster position="top-center" />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
